apiVersion: apps/v2
kind: Deployment
metadata:
  name: first-deployment
spec:
  selector:
    matchLabels:
      tags: Fundamental
  replicas: 2
  template:
    metadata:
      name: my-pod
      labels:
        tags: Fundamental
    spec:
      containers:
        - name: my-container
          image: hello-world:latest